#!/usr/bin/env python3
"""
Outlines the Superextra wordmark + tagline in SF Pro Light, once, into vector
path data → src/lib/brand/brand-glyphs.js.

Why: the brand wordmark is `font-weight: 300` over a `-apple-system, …, 'Inter'`
stack. That only renders Light when it resolves to SF Pro (Apple devices); the
Inter webfont has no 300 face, so everywhere else weight 300 snaps to 400
Regular — and SVG/PNG exports, which reference the font by name only, lose SF
entirely off-Apple. Outlining the glyphs makes every export carry true SF Pro
Light as paths, font-independent, in any viewer.

SF Pro's weight axis is non-linear: CSS `font-weight: 300` (Light) maps to the
variable `wght = 274.315` named instance, NOT 300 — so we instance there to match
on-screen rendering exactly. Optical size: the wordmark is a display lockup
(opsz 96); the tagline is small supporting text (opsz 30).

This is a one-time / on-demand step (like encrypt-brand): the JS output is
committed, so neither the build nor the runtime needs fontTools or SF Pro. Re-run
only when the wordmark/tagline strings or the source font change — requires SF
Pro present (macOS): `python3 scripts/build-brand-glyphs.py`.
"""
import json
import os
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

SFNS = "/System/Library/Fonts/SFNS.ttf"
LIGHT = 274.315  # CSS font-weight:300 → SF Pro "Light" named instance (wght axis)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src/lib/brand/brand-glyphs.js")


def instance(opsz):
    f = TTFont(SFNS)
    instantiateVariableFont(
        f, {"wght": LIGHT, "opsz": opsz, "wdth": 100, "GRAD": 400}, inplace=True
    )
    return f


def layout(f, text, ls_em):
    """SVG path (font units, y-up, baseline y=0, first glyph at x=0) + advance."""
    upm = f["head"].unitsPerEm
    cmap = f.getBestCmap()
    gs = f.getGlyphSet()
    hmtx = f["hmtx"]
    pen = SVGPathPen(gs)
    x = 0.0
    ls = ls_em * upm
    for ch in text:
        name = cmap[ord(ch)]
        gs[name].draw(TransformPen(pen, (1, 0, 0, 1, x, 0)))
        x += hmtx[name][0] + ls
    return pen.getCommands(), round(x, 2)


disp = instance(96)  # wordmark / monogram — display optical size
text = instance(30)  # tagline — text optical size
upm = disp["head"].unitsPerEm
os2 = disp["OS/2"]
hhea = disp["hhea"]

word_d, word_adv = layout(disp, "Superextra", -0.025)
s_d, s_adv = layout(disp, "S", -0.025)
tag_d, tag_adv = layout(text, "AI consultant for every restaurant", 0.01)

data = {
    # All paths are in font units (y-up, alphabetic baseline at y=0, first glyph
    # at x=0). Render with: translate(x, baseline) scale(size/upm, -size/upm).
    "upm": upm,
    "capHeight": os2.sCapHeight,
    "ascent": hhea.ascent,
    "descent": hhea.descent,
    "superextra": {"d": word_d, "adv": word_adv},
    "s": {"d": s_d, "adv": s_adv},
    "tagline": {"d": tag_d, "adv": tag_adv},
}

banner = (
    "// GENERATED by scripts/build-brand-glyphs.py — do not edit by hand.\n"
    "// Superextra wordmark + tagline outlined in SF Pro Light (wght 274.315), so\n"
    "// every SVG/PNG export carries the exact typeface as paths, font-independent.\n"
    "// Coords are font units (y-up, baseline at y=0); render with\n"
    "//   translate(x, baseline) scale(size/upm, -size/upm).\n"
)
with open(OUT, "w") as fh:
    fh.write(banner)
    for k in ("upm", "capHeight", "ascent", "descent"):
        fh.write(f"export const {k.upper() if k!='capHeight' else 'CAP_HEIGHT'} = {data[k]};\n")
    fh.write(f"export const SUPEREXTRA = {json.dumps(data['superextra'])};\n")
    fh.write(f"export const S = {json.dumps(data['s'])};\n")
    fh.write(f"export const TAGLINE = {json.dumps(data['tagline'])};\n")

print(f"Wrote {OUT}")
print(f"  upm={upm} capHeight={os2.sCapHeight} ascent={hhea.ascent} descent={hhea.descent}")
print(f"  Superextra adv={word_adv}  S adv={s_adv}  tagline adv={tag_adv}")
